[project]
name = "kazu"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Whth", email = "88489697+Whth@users.noreply.github.com"},
]
dependencies = [
    "pyuptech>=0.1.4a1",
    "mentabotix>=0.1.1a0",
    "bdmc>=0.1.3",
]
requires-python = "==3.11.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
