[project]
name = "kazu"
version = "0.1.0.dev0"
description = "Default template for PDM package"
authors = [
    {name = "Whth", email = "88489697+Whth@users.noreply.github.com"},
]
dependencies = [
    "mentabotix>=0.1.3a2",
    "pyuptech>=0.1.4",
    "bdmc>=0.1.5",
    "coloredlogs>=15.0.1",
    "pydantic>=2.7.1",
    "click>=8.1.7",
    "pyyaml>=6.0.1",
]
requires-python = "==3.11.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = true
