# 由 Kazu-v0.3.9 导出于 1749137568.888119
# ############################################################################ #

[motion]
# 右前电机配置。
motor_fr = [1, 1]
# 左前电机配置。
motor_fl = [2, 1]
# 右后电机配置。
motor_rr = [3, 1]
# 左后电机配置。
motor_rl = [4, 1]
# 通信使用的串口。
port = "/dev/ttyUSB0"

# ############################################################################ #

[vision]
# 视觉识别中的队伍颜色，允许 ["yellow", "blue","online"]。
team_color = "blue"
# 摄像头的分辨率倍数。
resolution_multiplier = 1.0
# 是否使用摄像头。
use_camera = true
# 摄像头设备 ID。
camera_device_id = 0

# ############################################################################ #

[debug]
# 调试日志等级，允许 ["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"]。
log_level = "INFO"
# 是否使用信号灯。
use_siglight = true

# ############################################################################ #

[sensor]
# 陀螺仪满量程范围，允许 [250, 500, 1000, 2000]。
gyro_fsr = 1000
# 加速度计满量程范围，允许 [2, 4, 8, 16]。
accel_fsr = 8
# ADC 最小采样间隔。
adc_min_sample_interval = 5
# 左前边缘传感器索引。
edge_fl_index = 3
# 右前边缘传感器索引。
edge_fr_index = 0
# 左后边缘传感器索引。
edge_rl_index = 2
# 右后边缘传感器索引。
edge_rr_index = 1
# 左侧 ADC 传感器索引。
left_adc_index = 6
# 右侧 ADC 传感器索引。
right_adc_index = 4
# 前侧 ADC 传感器索引。
front_adc_index = 5
# 后背 ADC 传感器索引。
rb_adc_index = 7
# 灰度 ADC 传感器索引。
gray_adc_index = 8
# 左侧灰度 IO 传感器索引。
gray_io_left_index = 1
# 右侧灰度 IO 传感器索引。
gray_io_right_index = 0
# 左前 IO 传感器索引。
fl_io_index = 5
# 右前 IO 传感器索引。
fr_io_index = 2
# 左后 IO 传感器索引。
rl_io_index = 4
# 右后 IO 传感器索引。
rr_io_index = 3
# 重启按钮索引。
reboot_button_index = 6

