# 由 Kazu-v0.3.9 导出于 2025-06-05 23:32:46.295874
# ############################################################################ #

[strategy]
# 是否使用边缘组件。
use_edge_component = true
# 是否使用周围组件。
use_surrounding_component = true
# 是否使用普通组件。
use_normal_component = true

# ############################################################################ #

[boot]
# 激活情况下的按钮输入输出值。
button_io_activate_case_value = 0
# 激活后稳定所需要的时间。
time_to_stabilize = 0.1
# 最大保持时长。
max_holding_duration = 180.0
# 左侧传感器的阈值。
left_threshold = 1100
# 右侧传感器阈值。
right_threshold = 1100
# 冲刺速度。
dash_speed = 7000
# 冲刺时间。
dash_duration = 0.55
# 转向速度。
turn_speed = 2150
# 完全转向时间。
full_turn_duration = 0.45
# 左转概率。
turn_left_prob = 0.5

# ############################################################################ #

[backstage]
# 激活后稳定所需要的时间。
time_to_stabilize = 0.1
# 小步前进速度。
small_advance_speed = 1500
# 小步前进时间。
small_advance_duration = 0.6
# 冲刺速度。
dash_speed = 7000
# 冲刺时间。
dash_duration = 0.55
# 转向速度。
turn_speed = 2600
# 完全转向时间。
full_turn_duration = 0.35
# 左转概率。
turn_left_prob = 0.5
# 是否检查是否在舞台上。
use_is_on_stage_check = true
# 在执行 is_on_stage 检查之后是否检查侧面离开。
use_side_away_check = true
# 定义在冲刺过程中何时进行 is_on_stage 检查。不要设置得太小！
check_start_percent = 0.9
# 边缘离开的角度容差。
side_away_degree_tolerance = 10.0
# 离开边缘的速度。
exit_side_away_speed = 1300
# 离开边缘的持续时间。
exit_side_away_duration = 0.6

# ############################################################################ #

[stage]
# 灰色ADC离台的上限阈值。
gray_adc_off_stage_upper_threshold = 2630
# 灰色ADC离台下限阈值。
gray_adc_on_stage_lower_threshold = 2830
# 判断车辆在模糊区域状态下是否处于舞台上的容差。
unclear_zone_tolerance = 90
# 模糊区域转向速度。
unclear_zone_turn_speed = 1500
# 模糊区域转向时间。
unclear_zone_turn_duration = 0.6
# 左转概率。
unclear_zone_turn_left_prob = 0.5
# 离场灰度IO值。
gray_io_off_stage_case_value = 0

# ############################################################################ #

[edge]
# 边缘检测的下阈值。
lower_threshold = [1740, 1819, 1819, 1740]
# 边缘检测的上阈值。
upper_threshold = [2100, 2470, 2470, 2100]
# 撤退速度。
fallback_speed = 2600
# 撤退时间。
fallback_duration = 0.2
# 前进速度。
advance_speed = 2400
# 前进时间。
advance_duration = 0.35
# 转向速度。
turn_speed = 2800
# 完全转向时间。
full_turn_duration = 0.45
# 半转向时间。
half_turn_duration = 0.225
# 左转概率。
turn_left_prob = 0.5
# 漂移速度。
drift_speed = 1500
# 漂移时间。
drift_duration = 0.13
# 是否使用灰度传感器。
use_gray_io = true

# ############################################################################ #

[surrounding]
# 遇到物体IO值。
io_encounter_object_value = 0
# 左传感器ADC下阈值。
left_adc_lower_threshold = 1000
# 右传感器ADC下阈值。
right_adc_lower_threshold = 1000
# 前传感器ADC下阈值。
front_adc_lower_threshold = 1000
# 后传感器ADC下阈值。
back_adc_lower_threshold = 1100
# 攻击中断时前ADC下阈值。
atk_break_front_lower_threshold = 1500
# 是否在攻击中断时使用边缘传感器。
atk_break_use_edge_sensors = true
# 攻击敌方车辆速度。
atk_speed_enemy_car = 2300
# 攻击敌方方块速度。
atk_speed_enemy_box = 2500
# 攻击中立方块速度。
atk_speed_neutral_box = 2500
# 后撤友方方块速度。
fallback_speed_ally_box = 2900
# 边缘后退速度。
fallback_speed_edge = 2400
# 攻击敌方车辆时间。
atk_enemy_car_duration = 4.2
# 攻击敌方方块时间。
atk_enemy_box_duration = 3.6
# 攻击中立方块时间。
atk_neutral_box_duration = 3.6
# 后撤友方方块时间。
fallback_duration_ally_box = 0.3
# 后撤边缘时间。
fallback_duration_edge = 0.2
# 转向速度。
turn_speed = 2900
# 左转概率。
turn_left_prob = 0.5
# 是否在"转向正前方"动作中使用前向传感器。
turn_to_front_use_front_sensor = false
# 随机转向速度列表。
rand_turn_speeds = [1600, 2100, 3000]
# 随机转向速度对应的权重。
rand_turn_speed_weights = [2, 3, 1]
# 完全转向时间。
full_turn_duration = 0.45
# 半转向时间。
half_turn_duration = 0.225

# ############################################################################ #

[search]
# 是否使用梯度移动。
use_gradient_move = true
# 梯度移动权重。
gradient_move_weight = 100
# 是否使用扫描移动。
use_scan_move = true
# 扫描移动权重。
scan_move_weight = 1.96
# 是否使用随机转动。
use_rand_turn = false
# 随机转动权重。
rand_turn_weight = 0.05
# ############################################################################ #
# 梯度移动配置。

[search.gradient_move]
# 梯度移动速度最大值。
max_speed = 2800
# 梯度移动速度最小值。
min_speed = 500
# 梯度移动下限值。
lower_bound = 2900
# 梯度移动上限值。
upper_bound = 3700

# ############################################################################ #
# 扫描移动配置。

[search.scan_move]
# 前传感器最大容差。
front_max_tolerance = 760
# 后传感器最大容差。
rear_max_tolerance = 760
# 左传感器最大容差。
left_max_tolerance = 760
# 右传感器最大容差。
right_max_tolerance = 760
# 遇到物体的IO值。
io_encounter_object_value = 0
# 扫描速度。
scan_speed = 300
# 扫描时间。
scan_duration = 4.5
# 扫描过程中左转概率。
scan_turn_left_prob = 0.5
# 撤退速度。
fall_back_speed = 3250
# 撤退时间。
fall_back_duration = 0.2
# 转向速度。
turn_speed = 2700
# 左转概率。
turn_left_prob = 0.5
# 完全转向时间。
full_turn_duration = 0.45
# 半转向时间。
half_turn_duration = 0.225
# 扫描之前是否检查边缘。
check_edge_before_scan = true
# 扫描之前是否检查灰度ADC。
check_gray_adc_before_scan = true
# 扫描时灰度ADC下阈值。
gray_adc_lower_threshold = 3100

# ############################################################################ #
# 随机转向配置。

[search.rand_turn]
# 转向速度。
turn_speed = 2300
# 左转概率。
turn_left_prob = 0.5
# 完全转向时间。
full_turn_duration = 0.25
# 半转向时间。
half_turn_duration = 0.15
# 是否启用转向正前方。
use_turn_to_front = true


# ############################################################################ #

[fence]
# 前ADC下阈值。
front_adc_lower_threshold = 900
# 后ADC下阈值。
rear_adc_lower_threshold = 1100
# 左ADC下阈值。
left_adc_lower_threshold = 900
# 右ADC下阈值。
right_adc_lower_threshold = 900
# 遇到围栏的IO值。
io_encounter_fence_value = 0
# 最大偏航角容差。
max_yaw_tolerance = 20.0
# 是否使用MPU进行舞台对齐。
use_mpu_align_stage = false
# 是否使用MPU进行方向对齐。
use_mpu_align_direction = false
# 舞台对齐时的速度。
stage_align_speed = 850
# 舞台对齐的最大持续时间。
max_stage_align_duration = 4.5
# 舞台对齐时的转向方向，可选 ["l", "r", "rand"]。
stage_align_direction = "rand"
# 方向对齐速度。
direction_align_speed = 850
# 方向对齐最大时间。
max_direction_align_duration = 4.5
# 平行或垂直方向对齐时的转向方向，可选 ["l", "r", "rand"]。
direction_align_direction = "rand"
# 退出角落速度。
exit_corner_speed = 1200
# 退出角落最大时间。
max_exit_corner_duration = 1.5
# ############################################################################ #
# 随机行走配置。

[fence.rand_walk]
# 是否使用直线移动。
use_straight = true
# 直线移动权重。
straight_weight = 2
# 随机速度。
rand_straight_speeds = [-800, -500, 500, 800]
# 随机速度权重。
rand_straight_speed_weights = [1, 3, 3, 1]
# 是否使用转向。
use_turn = true
# 转向权重。
turn_weight = 1
# 随机转向速度。
rand_turn_speeds = [-1200, -800, 800, 1200]
# 随机转向速度权重。
rand_turn_speed_weights = [1, 3, 3, 1]
# 行走时间。
walk_duration = 0.3


# ############################################################################ #

[perf]
# 检查时间。
checking_duration = 0.0

